config/routes.rb
Rails.application.routes.draw do

  resources :microposts
  resources :groups
  devise_for :users
  resources :users
  get 'users/:id' => 'users#show'
  resources :welcome
  root 'welcome#index'


  namespace :api do
    namespace :v1 do
      resources :microposts, only: [:index, :create, :destroy, :update]
    end
  end

  #   get 'products/:id' => 'catalog#view'

  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :users_groups
  has_many :users, through: :users_groups
  belongs_to :founder, class_name: User, foreign_key: :founder_id
  validates :group_name, presence: true

  def self.text_search(query)
    if query.present?
      where("group_name @@ :q or group_description @@ :q", q: query)
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
end

app/models/users_group.rb
class UsersGroup < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/microposts_controller.rb
class Api::V1::MicropostsController < Api::V1::BaseController
  def index
    respond_with Micropost.all
  end

  def create
    respond_with :api, :v1, Micropost.create(micropost_params)
    # Micropost.create(params[:user_id] == current_user.id)
  end

  def destroy
    respond_with Micropost.destroy(params[:id])
  end

  def update
    micropost = Micropost.find(params["id"])
    micropost.update_attributes(micropost_params)
    respond_with micropost, json: micropost
  end

 private

  def micropost_params
    params.require(:micropost).permit(:id, :content, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if params[:query]
      @groups = Group.text_search(params[:query])
      if params[:query].blank?
        @groups = Group.all
      else
      end
    else 
      @groups = Group.all
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_name, :group_description)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    # @micropost = Micropost.new(micropost_params)
    @micropost = Micropost.build(micropost_params)
    @micropost.user_id = current_user.id 

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.fetch(:micropost, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def show
     @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
      else
        format.json { render json: 'error', status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :email, :phone)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification

  .form-inputs
    = f.input :group_name
    = f.input :group_description

  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

= form_tag groups_path, :method => 'get' do |f|  
  = text_field_tag :query, params[:query], placeholder: "Search groups...", class: "form-control"
  %button.btn.btn-default{:type => "button"} Go!

%table
  %thead
    %tr
      %th Group Name
      %th Description

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.group_name
        %td= group.group_description
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

Group Name
= @group.group_name
%br

Group Description
= @group.group_description

%p Members:
%br


= link_to "Add me to this group!", root_path

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-fixed-top.navbar-full.navbar-light.bg-faded
  %ul.nav.nav-tabs
    %li.nav-item
      = link_to "Home", root_path
    %li.nav-item
      = link_to "Groups", groups_path
    %li.nav-item
      = link_to "Users", users_path
    %li.nav-item
      = link_to "Microposts", microposts_path

.pull-xs-right
  - if current_user.nil?
    = link_to 'Login', new_user_session_path, class: 'btn btn-primary'
    = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' 
  - else
    = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning'	

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %title SORA
    

= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
= javascript_include_tag 'application', 'data-turbolinks-track' => true
= csrf_meta_tags

%body
  = render "layouts/header"
  / = render 'shared/error_messages'
  
  .notice
    = notice
  .alert
    = alert

  = yield

:css

app/views/microposts/_form.html.haml
= simple_form_for(@micropost) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/microposts/edit.html.haml
%h1 Editing micropost

= render 'form'

= link_to 'Show', @micropost
\|
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
= react_component 'Main'

app/views/microposts/new.html.haml
%h1 New micropost

= render 'form'

= link_to 'Back', microposts_path

app/views/microposts/show.html.haml
- provide :title, "Post by #{@micropost.user.username}"
- provide :header do
  %h1
    = "Post by #{@micropost.user.username}"
    %small= format_time @micropost.created_at

= render 'micropost', micropost: @micropost

app/views/users/index.html.haml
.container
  - @users.each do |user|
    = link_to "#{user.email}", user_path(user)

app/views/users/show.html.haml
%p#notice= notice

= @user.id
= @user.email

app/views/welcome/_splash.html.haml
Go to /micrposts to see the react issue

Go to /groups to see the groups issue

app/views/welcome/index.html.haml
= render 'splash'

= yield